# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News', models.TextField()),
                ('Source', models.TextField(max_length=200)),
            ],
        ),
    ]
