# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Source',
            field=models.CharField(max_length=200),
        ),
    ]
